site_name: Code Capsules

theme:
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.sections
  name: material
  logo: assets/cclogo.png

  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: white
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Getting Started: index.md
  - Deployment:
    - Overview: deployment/index.md
    - Angular: deployment/how-to-deploy-angular-application-to-production.md
    - Express: deployment/how-to-deploy-express-application-to-production.md
    - Flask: deployment/how-to-deploy-flask-application-to-production.md
    - Java: deployment/how-to-deploy-java-application-to-production.md
    - React: deployment/how-to-deploy-react-application-to-production.md
    - HTML: deployment/how-to-deploy-static-html-to-production.md
    - Vue: deployment/how-to-deploy-vue-application-to-production.md
  - Reference: 
    - Overview: reference/index.md
    - Custom Domains: reference/custom_domains.md
    - Create and Connect MongoDB Data Capsule: reference/set-up-mongodb-data-capsule.md 
    - Create and Connect MySQL Data Capsule: reference/set-up-mysql-data-capsule.md
  - Tutorials: 
    - tutorials/index.md
    - Slackbot with Node.js: tutorials/build-slackbot-with-node.md
    - Web File Store: tutorials/build-a-web-file-store.md
    - Telegram Bot: tutorials/create-and-host-telegram-bot.md
    - Flask API: tutorials/creating-and-hosting-a-flask-api.md
    - Customising Domain: tutorials/customising-domain.md
    - Persistent Sleep Tracker Part 1: tutorials/develop-persistent-sleep-tracker-part-1.md
    - Persistent Sleep Tracker Part 2: tutorials/develop-persistent-sleep-tracker-part-2.md
    - Front-end Portfolio: tutorials/host-a-frontend.md
    - Stripe Checkout and Email Subscription with Flask: tutorials/stripe-checkout-and-email-with-flask.md
  - FAQ: 
    - Teams, Spaces and Capsules: FAQ/teams-spaces-capsules.md
    - What is a Capsule?: FAQ/what-is-a-capsule.md
    - What is a Space?: FAQ/what-is-a-space.md
    - What is a Team?: FAQ/what-is-a-team.md
    - How Do I Add a Custom Domain?: FAQ/how-to-add-custom-domain.md
  - Comparisons:
    - comparisons/index.md
    - PaaS Providers: comparisons/comparing-paas-providers-heroku-vs-digitalocean-vs-code-capsules.md
    - SaaS vs PaaS vs IaaS: comparisons/saas-paas-iaas.md
  - Community:
    - Introducing Code Capsules: community/introducing-code-capsules.md
    - Hack Days and Free Tech Consulting: community/codecapsules-hack-days.md
    - Founder Fridays: community/founder-fridays.md

extra:
  generator: false
  analytics:
    provider: google
    property: UA-165274631-2

plugins:
  - social
